version: 2.1
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3

# Define the jobs we want to run for this project
jobs:
  create_infrastructure: # Choose any name, such as `build`
    # The primary container, where your job's commands will run
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  config_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints: ["68:08:b8:3e:91:1f:28:84:4d:f2:5e:95:c2:16:e6:b9"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
            ansible-playbook -i inventory main-remote.yml



# Sequential workflow
workflows:
  udacityCICDWorkflow:
    jobs:
      - config_infrastructure
